name: bicep-build-deploy

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  plan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Azure Login with SPN
        uses: Azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Bicep Plan with WHAT-IF
        run: |
          echo "Planning to create resources"
          az deployment sub what-if \
            --name dev \
            --location eastus \
            --template-file dev.bicep \
            --parameters dev.parameters.json

  deploy:
    needs: plan
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Azure Login with SPN
        uses: Azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy Bicep Template
        run: |
          echo "Deploying resources"
          az deployment sub create \
            --name dev \
            --location eastus \
            --template-file dev.bicep \
            --parameters dev.parameters.json
